### ISSUE TITLE
Rate-Limits

### ISSUE THREAD

**Issue by C9Glax** [frnono/MangaDex-Fast-Downloader#1]
I took a glance at your code and couldn't find any rate-limiting, which will probably get people timed-out or worse ip-banned.

https://api.mangadex.org/docs/rate-limits/

Maybe take a look if it isn't too much of a hassle.

**Comment by frnono** [comment]
True true, I didn't think it was necessary because it doesn't do that many requests. After looking more into it, it would prob do 4 requests in a single second max. Though it's true that if you were to run multiple instances at once it might become an issue so next time I have time I will try to add a limit

**Comment by frnono** [comment]
I added a rate limit of 5 per second, thank you
